services:
  postgres:
    image: postgres:18
    container_name: postgres-itsm-db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itsmapiDB
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: