spring.application.name=itsm-api

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5430/itsmapiDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
